recClass = mbo.getString("RELATEDRECCLASS")
if (recClass=='WORKORDER' or recClass=='ACTIVITY') :
    mbo.setValue("E3MRELNPLOCATION",locVal,11l)
    mbo.setValue("E3MRELSTATUS",status,11l)
    mbo.setValue("E3MRELDESC",desc,11l)
    mbo.setValue("E3MRELNPASSETNUM",asstNum,11l)
    mbo.setValue("E3MRELREPBY",repBy,11l)
    mbo.setValue("E3MRELREPDATE",repDate,11l)
    mbo.setValue("E3MRELPRIORITY",priority,11l)
else :
    mbo.setValue("E3MRELNPLOCATION",srLocVal,11l)
    mbo.setValue("E3MRELSTATUS",srStatus,11l)
    mbo.setValue("E3MRELDESC",srDesc,11l)
    mbo.setValue("E3MRELNPASSETNUM",srasstNum,11l)
    mbo.setValue("E3MRELREPBY",srRepBy,11l)
    mbo.setValue("E3MRELREPDATE",srRepDate,11l)
    mbo.setValue("E3MRELPRIORITY",srPriority,11l)